export const buildingActionTypes = {
  SET_BUILDING_NAME: 'SET_BUILDING_NAME',
  SET_BUILDING_LOCATION: 'SET_BUILDING_LOCATION',
  INCRAMENT: 'INCRAMENT',
  DECRAMENT: 'DECRAMENT',
  SELECT_PANELS_NUM: 'SELECT_PANELS_NUM',
  SET_YEAR: 'SET_YEAR',
  CHECK_ITEM: 'CHECK_ITEM',
  UNCHECK_ITEM: 'UNCHECK_ITEM',
};
